import React from 'react';
import { Download, FileText, CheckCircle, AlertTriangle, ShieldX, Activity } from 'lucide-react';
import { useLivePolling } from '../hooks/useLivePolling';
import { useAuth } from '../context/AuthContext';

const Reports = () => {
  const { activeChild } = useAuth();
  const data = useLivePolling('/api/reports/full');

  if (!activeChild || !activeChild.isPaired) {
    return (
      <div className="animate-fade-in" style={{ padding: '60px', textAlign: 'center', maxWidth: '600px', margin: '0 auto' }}>
        <ShieldX size={64} color="var(--accent-purple)" style={{ marginBottom: '24px' }} />
        <h2 style={{ fontSize: '24px', fontWeight: 'bold', marginBottom: '16px' }}>Device Not Connected</h2>
        <p style={{ color: 'var(--text-muted)', lineHeight: '1.6' }}>Reports cannot be generated without an active connection. Please link a child device to begin compiling historical behavioral analysis.</p>
      </div>
    );
  }

  if(!data) return <div className="animate-fade-in" style={{ padding: '24px', textAlign: 'center' }}>Synchronizing reporting data...</div>;

  const handleDownload = () => {
    if (!data) return;
    const lines = [
      '══════════════════════════════════════════════════════',
      '        ALPHAGUARD AI — PARENTAL INSIGHTS REPORT',
      '══════════════════════════════════════════════════════',
      `Generated: ${new Date().toLocaleString()}`,
      `Child: ${activeChild?.name || 'Unknown'}`,
      '',
      '── SUMMARY ──────────────────────────────────────────',
      `Average Daily Screen Time: ${data.last30DaysSummary?.averageDailyFormatted || '0h 00m'}`,
      `Risk Score: ${data.riskScore}/100 (${data.riskLevel})`,
      `Security Flags: ${data.alertCount}`,
      '',
      '── TOP APPS ─────────────────────────────────────────',
      ...(data.topApps || []).map((app, i) => `  ${i + 1}. ${app.name} — ${app.time}`),
      '',
      `Most Watched Category: ${data.mostWatchedCategory || 'N/A'}`,
      '',
      '── SAFETY RECOMMENDATIONS ───────────────────────────',
      ...(data.recommendations || []).map((r, i) => `  ${i + 1}. ${r}`),
      '',
      '── CRITICAL INCIDENTS ───────────────────────────────',
      ...(data.flags && data.flags.length > 0 ? data.flags.map((f, i) => `  ${i + 1}. ${f}`) : ['  No critical incidents documented.']),
      '',
      '══════════════════════════════════════════════════════',
      '  This report was generated by AlphaGuard AI.',
      '  All data is encrypted and private.',
      '══════════════════════════════════════════════════════'
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `AlphaGuard-Report-${activeChild?.name || 'child'}-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="animate-fade-in" style={{ maxWidth: '1000px', margin: '0 auto', paddingBottom: '60px' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '32px' }}>
        <div>
          <h2 style={{ fontSize: '24px', fontWeight: '800' }}>Parental Insights Report</h2>
          <p style={{ color: 'var(--text-muted)', marginTop: '4px' }}>Detailed behavioral analysis for the past 30 days.</p>
        </div>
        <div style={{ display: 'flex', gap: '12px' }}>
           <div style={{ padding: '8px 16px', background: 'rgba(16, 185, 129, 0.1)', borderRadius: '8px', color: 'var(--accent-green)', fontSize: '12px', fontWeight: 'bold', border: '1px solid rgba(16, 185, 129, 0.2)' }}>
              DATA VERIFIED
           </div>
           <button onClick={handleDownload} style={{ 
            display: 'flex', alignItems: 'center', gap: '8px', padding: '10px 20px', 
            background: 'var(--accent-purple)', border: 'none',
            borderRadius: '8px', color: '#fff', cursor: 'pointer', fontWeight: 'bold'
          }}>
            <Download size={16} /> DOWNLOAD REPORT
          </button>
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '20px', marginBottom: '32px' }}>
         <div className="glass-card" style={{ padding: '24px' }}>
            <div style={{ color: 'var(--text-muted)', fontSize: '13px', marginBottom: '8px' }}>AVG DAILY SCREEN TIME</div>
            <div style={{ fontSize: '28px', fontWeight: '800', color: 'var(--accent-cyan)' }}>{data.last30DaysSummary?.averageDailyFormatted || '0h 00m'}</div>
            <div style={{ fontSize: '12px', color: 'var(--text-muted)', marginTop: '8px' }}>Based on last 30 days</div>
         </div>
         <div className="glass-card" style={{ padding: '24px' }}>
            <div style={{ color: 'var(--text-muted)', fontSize: '13px', marginBottom: '8px' }}>RISK SCORE (LIVE)</div>
            <div style={{ fontSize: '28px', fontWeight: '800', color: data.riskScore > 70 ? 'var(--accent-green)' : '#f59e0b' }}>{data.riskScore}/100</div>
            <div style={{ fontSize: '12px', color: 'var(--text-muted)', marginTop: '8px' }}>{data.riskLevel} alert status</div>
         </div>
         <div className="glass-card" style={{ padding: '24px' }}>
            <div style={{ color: 'var(--text-muted)', fontSize: '13px', marginBottom: '8px' }}>SECURITY FLAGS</div>
            <div style={{ fontSize: '28px', fontWeight: '800', color: data.alertCount > 0 ? 'var(--accent-red)' : '#fff' }}>{data.alertCount}</div>
            <div style={{ fontSize: '12px', color: 'var(--text-muted)', marginTop: '8px' }}>Total incidents detected</div>
         </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '24px' }}>
         
         <div className="glass-card" style={{ padding: '24px' }}>
            <h3 style={{ fontSize: '18px', marginBottom: '20px', display: 'flex', alignItems: 'center', gap: '8px' }}>
               <Activity size={18} color="var(--accent-cyan)" /> Activity Breakdown
            </h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
               {data.topApps?.map((app, i) => (
                  <div key={app.name} style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                     <div style={{ width: '8px', height: '8px', borderRadius: '50%', background: app.color }} />
                     <div style={{ flex: 1, fontSize: '14px' }}>{app.name}</div>
                     <div style={{ fontSize: '14px', fontWeight: 'bold' }}>{app.time}</div>
                  </div>
               ))}
            </div>
            <div style={{ marginTop: '32px', paddingTop: '20px', borderTop: '1px solid rgba(255,255,255,0.05)' }}>
               <div style={{ fontSize: '14px', fontWeight: '600', marginBottom: '12px' }}>Most Watched Category</div>
               <div style={{ padding: '12px', background: 'rgba(37,99,235, 0.1)', color: 'var(--accent-cyan)', borderRadius: '8px', textAlign: 'center', fontWeight: 'bold' }}>
                  {data.mostWatchedCategory || 'N/A'}
               </div>
            </div>
         </div>

         <div className="glass-card" style={{ padding: '24px' }}>
            <h3 style={{ fontSize: '18px', marginBottom: '20px', display: 'flex', alignItems: 'center', gap: '8px' }}>
               <FileText size={18} color="var(--accent-purple)" /> Safety Recommendations
            </h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
               {(data.recommendations || []).map((rec, i) => (
                  <div key={i} style={{ display: 'flex', gap: '12px', padding: '12px', background: 'rgba(255,255,255,0.02)', borderRadius: '8px', border: '1px solid rgba(255,255,255,0.03)' }}>
                     <CheckCircle size={16} color="var(--accent-green)" style={{ flexShrink: 0, marginTop: '2px' }} />
                     <p style={{ fontSize: '13px', lineHeight: 1.5, color: 'var(--text-secondary)' }}>{rec}</p>
                  </div>
               ))}
               {(!data.recommendations || data.recommendations.length === 0) && (
                 <p style={{ color: 'var(--text-muted)', fontSize: '14px' }}>Continuing monitoring to generate insights...</p>
               )}
            </div>
         </div>

      </div>

      <div className="glass-card" style={{ marginTop: '24px', padding: '24px' }}>
         <h3 style={{ fontSize: '18px', marginBottom: '20px', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <ShieldX size={18} color="var(--accent-red)" /> Critical Incidents Log
         </h3>
         <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
            {data.flags?.map((flag, i) => (
               <div key={i} style={{ display: 'flex', alignItems: 'center', gap: '12px', padding: '12px', background: 'rgba(239, 68, 68, 0.05)', border: '1px solid rgba(239, 68, 68, 0.1)', borderRadius: '8px' }}>
                  <AlertTriangle size={16} color="var(--accent-red)" />
                  <span style={{ fontSize: '13px', color: '#fff' }}>{flag}</span>
               </div>
            ))}
            {(!data.flags || data.flags.length === 0) && (
               <div style={{ textAlign: 'center', padding: '20px', color: 'var(--text-muted)' }}>
                  No critical security incidents documented in this period.
               </div>
            )}
         </div>
      </div>
    </div>
  );
};


export default Reports;
