import React, { useState } from 'react';
import { Download, FileText, CheckCircle, AlertTriangle, ShieldX, Activity, BarChart2, TrendingUp } from 'lucide-react';
import { useLivePolling } from '../hooks/useLivePolling';
import { useAuth } from '../context/AuthContext';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell, LineChart, Line } from 'recharts';
import { Card } from '../components/ui';

const InsightsHub = () => {
  const { activeChild, token } = useAuth();
  const [activeTab, setActiveTab] = useState('activity');

  const reportData = useLivePolling('/api/reports/full');
  const dashboardData = useLivePolling('/api/dashboard');

  if (!activeChild) {
    return (
      <div className="max-w-[520px] mx-auto mt-10 w-full">
        <Card tone="glass" className="p-8 text-center">
          <div className="w-16 h-16 rounded-3xl bg-blue-500/10 border border-blue-500/30 flex items-center justify-center mx-auto mb-5">
            <ShieldX size={32} className="text-cyan-400" />
          </div>
          <h2 className="text-xl font-black text-white mb-2.5">Insights Hub locked</h2>
          <p className="text-slate-400 text-[13px] leading-relaxed max-w-[360px] mx-auto">
            Link a child device to begin compiling safety diagnostics and usage charts.
          </p>
        </Card>
      </div>
    );
  }

  if (!reportData || !dashboardData) {
    return (
      <div className="h-[50vh] flex flex-col items-center justify-center gap-4">
        <div className="w-10 h-10 rounded-full border-[3px] border-white/10 border-t-cyan-500 animate-spin" />
        <div className="text-slate-500 text-[12px] font-bold uppercase tracking-widest">Compiling insights…</div>
      </div>
    );
  }

  const handleDownload = () => {
    if (!reportData) return;
    const lines = [
      '══════════════════════════════════════════════════════',
      '        ALPHAGUARD AI — PARENTAL INSIGHTS REPORT',
      '══════════════════════════════════════════════════════',
      `Generated: ${new Date().toLocaleString()}`,
      `Child ID: ${activeChild?.name || 'Device'}`,
      '',
      '── SUMMARY ──────────────────────────────────────────',
      `Average Daily Screen Time: ${reportData.last30DaysSummary?.averageDailyFormatted || '0h 00m'}`,
      `Risk Score: ${reportData.riskScore || 0}/100`,
      `Security Flags: ${reportData.alertCount || 0}`,
      '',
      '── TOP APPS ─────────────────────────────────────────',
      ...(reportData.topApps || []).map((app, i) => `  ${i + 1}. ${app.name} — ${app.time}`),
      '',
      `Most Watched Category: ${reportData.mostWatchedCategory || 'N/A'}`,
      '',
      '── SAFETY RECOMMENDATIONS ───────────────────────────',
      ...(reportData.recommendations || []).map((r, i) => `  ${i + 1}. ${r}`),
      '',
      '── CRITICAL INCIDENTS ───────────────────────────────',
      ...(reportData.flags && reportData.flags.length > 0 ? reportData.flags.map((f, i) => `  ${i + 1}. ${f}`) : ['  No critical incidents documented.']),
      '',
      '══════════════════════════════════════════════════════',
      '  This report was generated by AlphaGuard AI.',
      '  All data is encrypted and private.',
      '══════════════════════════════════════════════════════',
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `AlphaGuard-Report-${activeChild?.name || 'child'}-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const trendData = [{ name: 'W1', score: 90 }, { name: 'W2', score: 94 }, { name: 'W3', score: 92 }, { name: 'W4', score: 98 }];

  const TabHead = ({ icon: Icon, color, children }) => (
    <div className="flex items-center gap-2 text-[12px] font-black text-white tracking-tight border-b border-white/[0.06] pb-3 mb-3">
      <Icon size={15} style={{ color }} /> {children}
    </div>
  );

  return (
    <div className="flex flex-col gap-5 w-full max-w-[640px] mx-auto ag-rise">
      {/* Header */}
      <div className="flex items-center justify-between px-1">
        <div>
          <h1 className="text-[20px] font-black text-white tracking-tight leading-none">Insights Hub</h1>
          <p className="text-[12px] text-slate-500 font-semibold mt-1">Family safety analytics</p>
        </div>
        <button onClick={handleDownload} className="ag-tap flex items-center gap-1.5 py-2.5 px-4 bg-white/[0.05] border border-white/[0.07] rounded-full text-cyan-400 font-bold text-[12px]">
          <Download size={14} /> Export
        </button>
      </div>

      {/* Summary stats */}
      <div className="grid grid-cols-3 gap-2.5">
        {[
          { label: 'Avg Screen', val: reportData.last30DaysSummary?.averageDailyFormatted || '0h 00m', desc: '30 days' },
          { label: 'Risk Index', val: `${reportData.riskScore || 0}`, desc: 'of 100' },
          { label: 'Flags', val: reportData.alertCount || 0, desc: 'alerts' },
        ].map((c) => (
          <Card key={c.label} className="p-4">
            <span className="text-[10.5px] font-bold text-slate-500 uppercase tracking-wide block">{c.label}</span>
            <div className="text-[19px] font-black text-white tracking-tight mt-1.5 leading-none">{c.val}</div>
            <span className="text-[10.5px] text-slate-500 font-semibold">{c.desc}</span>
          </Card>
        ))}
      </div>

      {/* Tabs */}
      <div className="flex p-1 bg-white/[0.04] border border-white/[0.06] rounded-2xl">
        {[
          { id: 'activity', label: 'Activity' }, { id: 'reports', label: 'Reports' },
          { id: 'analytics', label: 'Analytics' }, { id: 'trends', label: 'Trends' },
        ].map((tab) => (
          <button key={tab.id} onClick={() => setActiveTab(tab.id)}
            className={`ag-tap flex-1 py-2.5 text-center text-[12.5px] font-bold rounded-xl transition-all ${activeTab === tab.id ? 'bg-[#0b0c14] text-cyan-400 shadow' : 'text-slate-400'}`}>
            {tab.label}
          </button>
        ))}
      </div>

      <div className="min-h-[250px]">
        {activeTab === 'activity' && (
          <Card tone="glass" className="p-5">
            <TabHead icon={Activity} color="#06b6d4">Activity Breakdown</TabHead>
            <div className="flex flex-col gap-3">
              {reportData.topApps && reportData.topApps.length > 0 ? reportData.topApps.map((app) => (
                <div key={app.name} className="flex items-center justify-between py-1.5 border-b border-white/[0.04] last:border-0 text-[13.5px] font-semibold">
                  <div className="flex items-center gap-2.5">
                    <span className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: app.color || '#4f46e5' }} />
                    <span className="text-white">{app.name}</span>
                  </div>
                  <span className="text-slate-400 font-bold">{app.time}</span>
                </div>
              )) : <div className="text-[12px] text-slate-500 py-6 text-center">No recent activity compiled.</div>}
            </div>
            <div className="mt-4 pt-4 border-t border-white/[0.06]">
              <div className="text-[11px] font-bold text-slate-500 uppercase tracking-wide mb-2">Dominant Category</div>
              <div className="py-3 px-4 bg-indigo-500/10 border border-indigo-500/20 text-indigo-300 rounded-2xl text-center text-[13px] font-black">
                {reportData.mostWatchedCategory || 'Pending'}
              </div>
            </div>
          </Card>
        )}

        {activeTab === 'reports' && (
          <div className="flex flex-col gap-4">
            <Card tone="glass" className="p-5">
              <TabHead icon={FileText} color="#6366f1">Safety Recommendations</TabHead>
              <div className="flex flex-col gap-2.5">
                {reportData.recommendations && reportData.recommendations.length > 0 ? reportData.recommendations.map((rec, i) => (
                  <div key={i} className="flex gap-2.5 p-3.5 bg-white/[0.03] border border-white/[0.06] rounded-2xl text-[13px] font-medium leading-relaxed text-slate-300">
                    <CheckCircle size={16} className="text-emerald-400 flex-shrink-0 mt-0.5" />
                    <span>{rec}</span>
                  </div>
                )) : <div className="text-[12px] text-slate-500 py-4 text-center">No recommendations yet.</div>}
              </div>
            </Card>
            <Card tone="glass" className="p-5">
              <TabHead icon={AlertTriangle} color="#f43f5e">Critical Incidents</TabHead>
              <div className="flex flex-col gap-2">
                {reportData.flags && reportData.flags.length > 0 ? reportData.flags.map((flag, i) => (
                  <div key={i} className="flex items-center gap-2.5 p-3.5 bg-rose-500/[0.06] border border-rose-500/15 rounded-2xl text-[13px] font-bold text-slate-200">
                    <AlertTriangle size={15} className="text-rose-500 flex-shrink-0" />
                    <span>{flag}</span>
                  </div>
                )) : <div className="text-[12px] text-slate-500 py-4 text-center">No critical incidents registered.</div>}
              </div>
            </Card>
          </div>
        )}

        {activeTab === 'analytics' && (
          <Card tone="glass" className="p-5">
            <TabHead icon={BarChart2} color="#06b6d4">Category Distribution (min)</TabHead>
            {dashboardData.categoryDistribution && dashboardData.categoryDistribution.length > 0 ? (
              <div className="w-full h-56 -ml-4 mt-1">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={dashboardData.categoryDistribution} margin={{ top: 10, right: 10, left: 0, bottom: 5 }}>
                    <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.04)" vertical={false} />
                    <XAxis dataKey="name" stroke="#475569" fontSize={10} tickLine={false} axisLine={false} />
                    <YAxis stroke="#475569" fontSize={10} tickLine={false} axisLine={false} />
                    <Tooltip cursor={{ fill: 'rgba(255,255,255,0.03)' }} contentStyle={{ backgroundColor: '#0b0c14', border: '1px solid rgba(255,255,255,0.08)', borderRadius: 12, color: '#fff', fontSize: 12 }} />
                    <Bar dataKey="value" radius={[5, 5, 0, 0]} maxBarSize={42}>
                      {dashboardData.categoryDistribution.map((entry, index) => <Cell key={index} fill={entry.color || '#06b6d4'} />)}
                    </Bar>
                  </BarChart>
                </ResponsiveContainer>
              </div>
            ) : <div className="text-[12px] text-slate-500 py-10 text-center">No category data recorded.</div>}
          </Card>
        )}

        {activeTab === 'trends' && (
          <Card tone="glass" className="p-5">
            <TabHead icon={TrendingUp} color="#6366f1">Weekly Safety Trend</TabHead>
            <div className="w-full h-56 -ml-4 mt-1">
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={trendData} margin={{ top: 10, right: 15, left: 0, bottom: 5 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.04)" vertical={false} />
                  <XAxis dataKey="name" stroke="#475569" fontSize={10} tickLine={false} axisLine={false} />
                  <YAxis stroke="#475569" fontSize={10} tickLine={false} axisLine={false} />
                  <Tooltip contentStyle={{ backgroundColor: '#0b0c14', border: '1px solid rgba(255,255,255,0.08)', borderRadius: 12, color: '#fff', fontSize: 12 }} />
                  <Line type="monotone" dataKey="score" stroke="#4f46e5" strokeWidth={2.5} dot={{ r: 4, stroke: '#030307', strokeWidth: 2 }} activeDot={{ r: 6 }} />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </Card>
        )}
      </div>
    </div>
  );
};

export default InsightsHub;
