import React, { useState } from 'react';
import { Download, FileText, CheckCircle, AlertTriangle, ShieldX, Activity, BarChart2, TrendingUp } from 'lucide-react';
import { useLivePolling } from '../hooks/useLivePolling';
import { useAuth } from '../context/AuthContext';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell, LineChart, Line } from 'recharts';

const InsightsHub = () => {
  const { activeChild, token } = useAuth();
  const [activeTab, setActiveTab] = useState('activity'); // 'activity' | 'reports' | 'analytics' | 'trends'

  // Fetch from both reporting and dashboard endpoints
  const reportData = useLivePolling('/api/reports/full');
  const dashboardData = useLivePolling('/api/dashboard');

  if (!activeChild) {
    return (
      <div className="glass-card max-w-[600px] mx-auto mt-16 p-10 text-center border border-white/5 backdrop-blur-md shadow-2xl font-sans">
        <div className="w-16 h-16 rounded-full bg-indigo-500/10 border border-indigo-500 flex items-center justify-center mx-auto mb-6">
          <ShieldX size={32} className="text-cyan-400" />
        </div>
        <h2 className="text-xl font-extrabold text-white mb-3">Insights Hub Locked</h2>
        <p className="text-slate-400 text-sm leading-relaxed max-w-[400px] mx-auto">
          Please link a child device to begin compiling historical safety diagnostics and usage charts.
        </p>
      </div>
    );
  }

  if (!reportData || !dashboardData) {
    return (
      <div className="h-[50vh] flex flex-col items-center justify-center gap-4 font-sans">
        <div className="w-10 h-10 rounded-full border-3 border-white/10 border-t-cyan-500 animate-spin" />
        <div className="text-slate-500 text-xs font-bold uppercase tracking-widest">Compiling Analytics & Logs...</div>
      </div>
    );
  }

  const handleDownload = () => {
    if (!reportData) return;
    const lines = [
      '══════════════════════════════════════════════════════',
      '        ALPHAGUARD OS — PARENTAL INSIGHTS REPORT',
      '══════════════════════════════════════════════════════',
      `Generated: ${new Date().toLocaleString()}`,
      `Child ID: ${activeChild?.name || 'Device'}`,
      '',
      '── SUMMARY ──────────────────────────────────────────',
      `Average Daily Screen Time: ${reportData.last30DaysSummary?.averageDailyFormatted || '0h 00m'}`,
      `Risk Score: ${reportData.riskScore || 0}/100`,
      `Security Flags: ${reportData.alertCount || 0}`,
      '',
      '── TOP APPS ─────────────────────────────────────────',
      ...(reportData.topApps || []).map((app, i) => `  ${i + 1}. ${app.name} — ${app.time}`),
      '',
      `Most Watched Category: ${reportData.mostWatchedCategory || 'N/A'}`,
      '',
      '── SAFETY RECOMMENDATIONS ───────────────────────────',
      ...(reportData.recommendations || []).map((r, i) => `  ${i + 1}. ${r}`),
      '',
      '── CRITICAL INCIDENTS ───────────────────────────────',
      ...(reportData.flags && reportData.flags.length > 0 ? reportData.flags.map((f, i) => `  ${i + 1}. ${f}`) : ['  No critical incidents documented.']),
      '',
      '══════════════════════════════════════════════════════',
      '  This report was generated by AlphaGuard OS.',
      '  All data is encrypted and private.',
      '══════════════════════════════════════════════════════'
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `AlphaGuard-Report-${activeChild?.name || 'child'}-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const trendData = [
    { name: 'W1', score: 90 },
    { name: 'W2', score: 94 },
    { name: 'W3', score: 92 },
    { name: 'W4', score: 98 },
  ];

  return (
    <div className="flex flex-col gap-5 px-3 pb-24 pt-4 max-w-[640px] mx-auto animate-fade-in font-sans">
      
      {/* Header bar */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-lg font-black text-white leading-none uppercase tracking-wider">Insights Hub</h2>
          <p className="text-[10px] text-slate-500 font-bold uppercase tracking-widest mt-1.5">Family safety os analytics</p>
        </div>
        <button 
          onClick={handleDownload}
          className="flex items-center gap-1.5 py-2 px-3.5 bg-white/5 border border-white/5 rounded-full text-cyan-400 font-black text-[10px] tracking-wider uppercase cursor-pointer hover:bg-white/10 active:scale-95 transition-all shadow-md"
        >
          <Download size={12} />
          <span>Export Logs</span>
        </button>
      </div>

      {/* Grid: 3 summary stats */}
      <div className="grid grid-cols-3 gap-3">
        {[
          { label: 'Avg Screen Time', val: reportData.last30DaysSummary?.averageDailyFormatted || '0h 00m', desc: 'Past 30 days' },
          { label: 'Risk Index', val: `${reportData.riskScore || 0}/100`, desc: 'Live Telemetry' },
          { label: 'Flags Logged', val: reportData.alertCount || 0, desc: 'Critical alerts' }
        ].map(card => (
          <div key={card.label} className="glass-card p-4 border border-white/5 rounded-2xl bg-white/[0.02] flex flex-col justify-between">
            <span className="text-[9px] font-black text-slate-500 uppercase tracking-wider leading-none mb-2">{card.label}</span>
            <div className="text-lg font-black text-white tracking-tight">{card.val}</div>
            <span className="text-[8.5px] text-slate-500 font-bold mt-1 leading-none">{card.desc}</span>
          </div>
        ))}
      </div>

      {/* Premium Glass tab bar navigation */}
      <div className="flex p-1 bg-white/5 border border-white/5 rounded-2xl backdrop-blur-md">
        {[
          { id: 'activity', label: 'Activity' },
          { id: 'reports', label: 'Reports' },
          { id: 'analytics', label: 'Analytics' },
          { id: 'trends', label: 'Trends' }
        ].map(tab => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={`flex-1 py-2 text-center text-[10px] font-black uppercase tracking-wider rounded-xl transition-all cursor-pointer ${activeTab === tab.id ? 'bg-[#0b0c14] text-cyan-400 shadow' : 'text-slate-400'}`}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* Dynamic Tab Contents */}
      <div className="min-h-[250px]">
        {activeTab === 'activity' && (
          <div className="glass-card p-4 border border-white/5 rounded-2xl bg-white/[0.02] flex flex-col gap-4 animate-fade-in">
            <div className="flex items-center gap-1.5 text-[10px] font-black text-slate-500 uppercase tracking-widest border-b border-white/5 pb-2">
              <Activity size={13} className="text-cyan-400" />
              <span>Activity Breakdown</span>
            </div>
            
            <div className="flex flex-col gap-3">
              {reportData.topApps && reportData.topApps.length > 0 ? (
                reportData.topApps.map(app => (
                  <div key={app.name} className="flex items-center justify-between border-b border-white/[0.02] pb-2 last:border-0 last:pb-0 text-xs font-semibold">
                    <div className="flex items-center gap-2">
                      <div className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: app.color || '#4f46e5' }} />
                      <span className="text-white">{app.name}</span>
                    </div>
                    <span className="text-slate-400 font-extrabold">{app.time}</span>
                  </div>
                ))
              ) : (
                <div className="text-[10px] text-slate-500 font-bold py-6 text-center">No recent application events compiled.</div>
              )}
            </div>

            <div className="mt-2 pt-4 border-t border-white/5">
              <div className="text-[9px] font-black text-slate-500 uppercase tracking-widest mb-2">Dominant Category</div>
              <div className="py-2.5 px-4 bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 rounded-xl text-center text-xs font-extrabold uppercase tracking-wider">
                {reportData.mostWatchedCategory || 'Pending'}
              </div>
            </div>
          </div>
        )}

        {activeTab === 'reports' && (
          <div className="flex flex-col gap-4 animate-fade-in">
            
            {/* Safety Recommendations */}
            <div className="glass-card p-4 border border-white/5 rounded-2xl bg-white/[0.02] flex flex-col gap-3">
              <div className="flex items-center gap-1.5 text-[10px] font-black text-slate-500 uppercase tracking-widest border-b border-white/5 pb-2">
                <FileText size={13} className="text-indigo-400" />
                <span>Safety Recommendations</span>
              </div>
              <div className="flex flex-col gap-2.5">
                {reportData.recommendations && reportData.recommendations.length > 0 ? (
                  reportData.recommendations.map((rec, i) => (
                    <div key={i} className="flex gap-2 p-3 bg-white/[0.02] border border-white/5 rounded-xl text-xs font-semibold leading-relaxed text-slate-300">
                      <CheckCircle size={14} className="text-emerald-400 flex-shrink-0 mt-0.5" />
                      <span>{rec}</span>
                    </div>
                  ))
                ) : (
                  <div className="text-[10px] text-slate-500 font-bold py-4 text-center">No safety instructions formulated yet.</div>
                )}
              </div>
            </div>

            {/* Critical Incidents Log */}
            <div className="glass-card p-4 border border-white/5 rounded-2xl bg-white/[0.02] flex flex-col gap-3">
              <div className="flex items-center gap-1.5 text-[10px] font-black text-slate-500 uppercase tracking-widest border-b border-white/5 pb-2">
                <AlertTriangle size={13} className="text-red-400" />
                <span>Critical Incidents Log</span>
              </div>
              <div className="flex flex-col gap-2">
                {reportData.flags && reportData.flags.length > 0 ? (
                  reportData.flags.map((flag, i) => (
                    <div key={i} className="flex items-center gap-2.5 p-3 bg-red-500/5 border border-red-500/10 rounded-xl text-xs font-bold text-slate-200">
                      <AlertTriangle size={14} className="text-red-500 flex-shrink-0" />
                      <span>{flag}</span>
                    </div>
                  ))
                ) : (
                  <div className="text-[10px] text-slate-500 font-bold py-4 text-center">No critical incidents registered in system storage.</div>
                )}
              </div>
            </div>

          </div>
        )}

        {activeTab === 'analytics' && (
          <div className="glass-card p-4 border border-white/5 rounded-2xl bg-white/[0.02] flex flex-col gap-4 animate-fade-in">
            <div className="flex items-center gap-1.5 text-[10px] font-black text-slate-500 uppercase tracking-widest border-b border-white/5 pb-2">
              <BarChart2 size={13} className="text-cyan-400" />
              <span>Category Distribution (Minutes)</span>
            </div>
            
            {dashboardData.categoryDistribution && dashboardData.categoryDistribution.length > 0 ? (
              <div className="w-full h-56 -ml-5 mt-2">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={dashboardData.categoryDistribution} margin={{ top: 10, right: 10, left: 0, bottom: 5 }}>
                    <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.03)" vertical={false} />
                    <XAxis dataKey="name" stroke="#64748b" fontSize={9} tickLine={false} axisLine={false} />
                    <YAxis stroke="#64748b" fontSize={9} tickLine={false} axisLine={false} />
                    <Tooltip 
                      cursor={{ fill: 'rgba(255,255,255,0.02)' }}
                      contentStyle={{ backgroundColor: '#0b0c14', border: '1px solid rgba(255,255,255,0.05)', borderRadius: '12px', color: '#fff' }}
                      itemStyle={{ color: '#fff', fontSize: '10px' }}
                    />
                    <Bar dataKey="value" radius={[4, 4, 0, 0]} maxBarSize={40}>
                      {dashboardData.categoryDistribution.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={entry.color || '#06b6d4'} />
                      ))}
                    </Bar>
                  </BarChart>
                </ResponsiveContainer>
              </div>
            ) : (
              <div className="text-[10px] text-slate-500 font-bold py-10 text-center">No telemetry data recorded for categories.</div>
            )}
          </div>
        )}

        {activeTab === 'trends' && (
          <div className="glass-card p-4 border border-white/5 rounded-2xl bg-white/[0.02] flex flex-col gap-4 animate-fade-in">
            <div className="flex items-center gap-1.5 text-[10px] font-black text-slate-500 uppercase tracking-widest border-b border-white/5 pb-2">
              <TrendingUp size={13} className="text-indigo-400" />
              <span>Weekly Safety index Trends</span>
            </div>
            
            <div className="w-full h-56 -ml-5 mt-2">
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={trendData} margin={{ top: 10, right: 15, left: 0, bottom: 5 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.03)" vertical={false} />
                  <XAxis dataKey="name" stroke="#64748b" fontSize={9} tickLine={false} axisLine={false} />
                  <YAxis stroke="#64748b" fontSize={9} tickLine={false} axisLine={false} />
                  <Tooltip 
                    contentStyle={{ backgroundColor: '#0b0c14', border: '1px solid rgba(255,255,255,0.05)', borderRadius: '12px', color: '#fff' }}
                    itemStyle={{ color: '#06b6d4', fontSize: '10px' }}
                  />
                  <Line 
                    type="monotone" 
                    dataKey="score" 
                    stroke="#4f46e5" 
                    strokeWidth={2.5} 
                    dot={{ r: 4, stroke: '#030307', strokeWidth: 2 }}
                    activeDot={{ r: 6 }} 
                  />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </div>
        )}
      </div>

    </div>
  );
};

export default InsightsHub;
